#!/bin/bash
#
# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

if [ -z "${DOCKERHUBUSER}" ]; then
	echo "Error: set environment variable DOCKERHUBUSER"
	exit 1
fi

if [ ! -e ../../MonteCarloInsideBlockingDP.avx512 ] || [ ! -e ../../MonteCarloInsideBlockingDP.avx2 ]; then
	echo "Error: compile Monte Carlo binary for AVX-512 and AVX2 before building Docker image"
	exit 1
fi

if [ ! -e ../../libiomp5.so ] || [ ! -e ../../libtbbmalloc.so.2 ]; then
	echo "Error: copy libraries libiomp5.so and libtbbmalloc.so.2 to .. before building Docker image"
	exit 1
fi

cp -u ../../MonteCarloInsideBlockingDP.avx512 ../../MonteCarloInsideBlockingDP.avx2 ../../libiomp5.so ../../libtbbmalloc.so.2 .

docker build . -t "${DOCKERHUBUSER}/montecarlo"
docker login
docker push "${DOCKERHUBUSER}/montecarlo"
