#
# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: montecarloavx2
  labels:
    name: montecarloavx2
spec:
  restartPolicy: Never
  #nodeSelector:
    #kubernetes.io/hostname: k8s-node1
  containers:
  - name: montecarlo
    image: ptorre/montecarlo
    imagePullPolicy: Always
    command: ["/app/start"]
    #command: ["sleep", "infinity"]
    env:
    - name: USE_TASKSET
      value: "1"
    - name: PAUSE_TIME # seconds
      value: "10"
    - name: PR # processes
      value: "2"
    - name: PUSHGWIP
      value: "192.168.0.235"
    resources:
      requests:
        memory: "500Mi"
        cpu: "2"
      limits:
        memory: "500Mi"
        cpu: "2"
